# Golangci configurations
# See: https://golangci-lint.run/usage/linters/

# Options for analysis running.
run:
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 5m

  # Allow multiple parallel golangci-lint instances running.
  # If false, golangci-lint acquires file lock on start.
  # Default: false
  allow-parallel-runners: true
  # Allow multiple golangci-lint instances running, but serialize them around a lock.
  # If false, golangci-lint exits with an error if it fails to acquire file lock on start.
  # Default: false
  allow-serial-runners: true

output:
  # colored-line-number|line-number|json|tab|checkstyle, default is "colored-line-number"
  formats: colored-line-number

linters:
  fast: false
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - depguard
    - gofmt
    - gofumpt
    - goimports
    - gci
    - gosec

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/brpaz/prom-dirsize-exporter)
    skip-generated: true
  gofmt:
    # Simplify code: gofmt with `-s` option.
    simplify: true
    # Apply the rewrite rules to the source before reformatting.
    # https://pkg.go.dev/cmd/gofmt
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
      - pattern: 'a[b:len(a)]'
        replacement: 'a[b:]'
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/brpaz/prom-dirsize-exporter
  gocyclo:
    min-complexity: 10
  gosec:
    severity: medium
    confidence: medium
    nosec: true
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitely denied
        files:
          - $all
          - "!$test"
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"


