# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: prom-dirsize-exporter
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    #- go generate ./...

# ==================================
# Build customization
# ==================================
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/brpaz/prom-dirsize-exporter/internal/version.Version={{.Version}} -X github.com/brpaz/prom-dirsize-exporter/internal/version.GitCommit={{.Commit}} -X github.com/brpaz/prom-dirsize-exporter/internal/version.BuildDate={{.Date}}

# ==================================
# Archive customization
# ==================================
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

# ==================================
# Package configurations
# ==================================
nfpms:
  # Template to your app's homepage.
  # Default is empty.
  - homepage: https://brunopaz.dev

    # Your app's maintainer (probably you).
    # Default is empty.
    maintainer: Bruno Paz <oss@brunopaz.dev

    # Template to your app's description.
    # Default is empty.
    description: |-
      A Prometheus exporter that exports metrics regarding the size of directories.

    # Your app's license.
    # Default is empty.
    license: MIT

    # Formats to be generated.
    formats:
      - deb
      - rpm
      - archlinux

# ==================================
# Other configurations
# ==================================
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
