name: Label Checker

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  statuses: write
  checks: write

jobs:
  check_labels:
    name: Check PR Labels
    runs-on: ubuntu-latest
    steps:
      - uses: danielchabr/pr-labels-checker@v3.3
        with:
          hasSome: feature,enhancement,bug,documentation,duplicate,security,chore,maintenance,dependencies
          githubToken: ${{ secrets.GITHUB_TOKEN }}
